import type { Metadata } from "next";
import "./globals.css";
import { BackgroundBeams } from "@/components/ui/background-beams";
import { Providers } from "./Provider";
import { Open_Sans  } from 'next/font/google';

const openSansFamily = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Deck: Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` bg-transparent ${openSansFamily.className} antialiased`}
      >
        <BackgroundBeams />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
