import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/lib/QueryProvider";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { NextThemeroviders } from "./Provider";

const openSansFamily = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Deck: Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${openSansFamily.className} antialiased`}
      >
        <QueryProvider>
          <NextThemeroviders>
            <main>
              {children}
              <Toaster />
            </main>
          </NextThemeroviders>
        </QueryProvider>
      </body>
    </html>
  );
}
